@startuml TrafficLight

Start -> Carlight Green 
CarLight Green -> Pedestrian Sensor
Pedestrian Sensor -> CarLight Green : False
Pedestrian Sensor -> Wait on Yellow : True
Wait on Yellow -> CarLight Yellow
CarLight Yellow -> Wait on Red
Wait on Red -> CarLight Red
CarLight Red -> Car Sensor
Car Sensor -> CarLight Red : False
Car Sensor -> Wait on Red for PedestrianLight : True
Wait on Red for PedestrianLight -> Wait on Red for PedestrianLight : Waiting
Wait on Red for PedestrianLight -> CarLight Green

Start -> PedestrianLight Red
PedestrianLight Red -> Wait on Red for CarLight
Wait on Red for CarLight -> PedestrianLight Red : CarLight Green
Wait on Red for CarLight -> PedestrianLight Green : CarLight Red
PedestrianLight Green -> Car Sensor
Car Sensor -> PedestrianLight Green : False
Car Sensor -> Blinker PedestrianLight : True, Wait for 5s
Blinker PedestrianLight -> PedestrianLight Red 
Blinker PedestrianLight -> Blinker PedestrianLight : Wait till blinker is finished

@enduml
