<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{f24a42c3-b030-4992-be5e-c24c89fa021d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR


END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CarTrafficLight();
PedestrianTrafficLight();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="175" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>