<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU" Id="{73589837-d2c9-40a7-9aee-c76a33b51521}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION POU : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>